export const domVariables = {
  prevBtn: document.querySelector('#prevMonth') as HTMLButtonElement,
  nextBtn: document.querySelector('#nextMonth') as HTMLButtonElement,
  currentMonthElement: document.getElementById('currentMonth') as HTMLHeadingElement,
  calendarDays: document.querySelector('.days') as HTMLDivElement,
  addEventButton: document.getElementById('showModal') as HTMLButtonElement,
  newEventModal: document.getElementById('newEventModal') as HTMLDivElement,
  closeModalButton: document.getElementById('closeModal') as HTMLButtonElement,
  cancelButton: document.getElementById('cancelButton') as HTMLButtonElement,
  newEventForm: document.getElementById('newEventForm') as HTMLFormElement,
  reminderSelect: document.getElementById('reminder') as HTMLFormElement,
  eventTitle: document.getElementById('eventTitle') as HTMLFormElement,
  initialDate: document.getElementById('initialDate') as HTMLFormElement,
  endDateContainer: document.querySelector('.endDate') as HTMLDivElement,
  endDate: document.getElementById('endDate') as HTMLFormElement,
  remindDate: document.getElementById('remindDate') as HTMLFormElement,
  reminderContainer: document.querySelector('.reminderContainer') as HTMLDivElement,
  eventType: document.getElementById('eventType') as HTMLFormElement,
  description: document.getElementById('description') as HTMLFormElement,
  checkEndDate: document.getElementById('checkEndDate') as HTMLFormElement,
  saveButton: document.getElementById('saveButton') as HTMLButtonElement
};